#pragma once
#include <vector>
#include <algorithm>
#include <map>
#include <parser/snapshot.hpp>
#include <parser/node.hpp>


/**
 * @brief Simple interface for analyzing various type of files generated by massif tool
*/
class IFixifAnalyzer
{
public:
    IFixifAnalyzer() {}
    virtual ~IFixifAnalyzer() {}
    /**
     * @brief Method which executes logic of fixif analyzer for certain type of file
    */
    virtual void run() = 0;
};
/**
 * @brief Class that implements logic of analyzing massif out files.
*/
class MassifAnalyzer : public IFixifAnalyzer
{
public:
    MassifAnalyzer(const std::vector<std::shared_ptr<Snapshot>> &snapshots, const std::shared_ptr<Snapshot> &peakSnapshot)
        : mSnapshots(snapshots), mPeakSnapshot(peakSnapshot)
    {
    }

    void run() override;

private:
    void processPeak();
    void processLastSnapshot();
    void processSnapshots();
    std::shared_ptr<Snapshot> mPeakSnapshot;
    std::vector<std::shared_ptr<Snapshot>> mSnapshots;
    std::shared_ptr<Snapshot> realPeakSnapshot;
};

/**
 * @brief Class that implements logic of analyzing xtmemory kcg files.
*/
class XtMemoryAnalyzer : public IFixifAnalyzer
{
public:
    XtMemoryAnalyzer(const std::shared_ptr<XTreeMemory> tree, const std::map<int, std::string>& fileMap)
        : xTree(tree), mFileMap(fileMap)
    {}
    void run() override;

private:
    std::shared_ptr<XTreeMemory> xTree;
    std::map<int, std::string> mFileMap;
    /**
     * @brief Function which appends important information from xtree to source file to be easier for overview.
     * @return Indicator of success  
    */
    bool appendToSource();
};